'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Release
    
    '''<summary>
    '''EmpInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmpInfo As Global.PolicyTracker.EmpInfo
    
    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''fvRelease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvRelease As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''lblFilterOrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFilterOrg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlFilterOrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFilterOrg As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''odsFilterOrg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsFilterOrg As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''fvRelStat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvRelStat As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''btnCreateData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateData As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCreateNotices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateNotices As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''vsMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsMain As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''tlMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tlMain As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tliPolicies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tliPolicies As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tlkPolicies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tlkPolicies As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''spnPolCnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnPolCnt As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tliRecipients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tliRecipients As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tlkRecipients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tlkRecipients As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''spnRecCnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnRecCnt As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tliNotices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tliNotices As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tlkNotices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tlkNotices As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''spnNotCnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnNotCnt As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblInfoPolicies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfoPolicies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblErrorPolicies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorPolicies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''vsPolicies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsPolicies As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''gvRelPolicies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvRelPolicies As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''gvFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvFiles As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblInfoUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfoUpload As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblErrorUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorUpload As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpload As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblInfoRecipients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfoRecipients As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblErrorRecipients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorRecipients As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''vsRecipients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsRecipients As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''gvRelRecipients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvRelRecipients As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnDownloadPackets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDownloadPackets As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''dvPacket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvPacket As Global.System.Web.UI.WebControls.DetailsView
    
    '''<summary>
    '''odsPacket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsPacket As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''lblDetailsViewMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailsViewMode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gvRelNotices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvRelNotices As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblInfoNotices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfoNotices As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblErrorNotices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorNotices As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''vsNotices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsNotices As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''dvRelNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvRelNotice As Global.System.Web.UI.WebControls.DetailsView
    
    '''<summary>
    '''odsRelNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRelNotice As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''lblDetailsViewModeRelNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetailsViewModeRelNotice As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As PolicyTracker.SiteMaster
        Get
            Return CType(MyBase.Master,PolicyTracker.SiteMaster)
        End Get
    End Property
End Class
