'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
'
Namespace HRWebService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WebServiceSoap", [Namespace]:="http://ci.long-beach.ca.us/")>  _
    Partial Public Class WebService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetHREmpByEmpIdOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetHREmpByDLNoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetHREmpsActiveOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetHRDepartmentsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetHRBureausOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetHRDivisionsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetHRClassificationsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.PolicyTracker.[Lib].My.MySettings.Default.PolicyTracker_Lib_HRWebService_WebService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetHREmpByEmpIdCompleted As GetHREmpByEmpIdCompletedEventHandler
        
        '''<remarks/>
        Public Event GetHREmpByDLNoCompleted As GetHREmpByDLNoCompletedEventHandler
        
        '''<remarks/>
        Public Event GetHREmpsActiveCompleted As GetHREmpsActiveCompletedEventHandler
        
        '''<remarks/>
        Public Event GetHRDepartmentsCompleted As GetHRDepartmentsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetHRBureausCompleted As GetHRBureausCompletedEventHandler
        
        '''<remarks/>
        Public Event GetHRDivisionsCompleted As GetHRDivisionsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetHRClassificationsCompleted As GetHRClassificationsCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ci.long-beach.ca.us/GetHREmpByEmpId", RequestNamespace:="http://ci.long-beach.ca.us/", ResponseNamespace:="http://ci.long-beach.ca.us/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetHREmpByEmpId(ByVal empId As String) As HREmp
            Dim results() As Object = Me.Invoke("GetHREmpByEmpId", New Object() {empId})
            Return CType(results(0),HREmp)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetHREmpByEmpIdAsync(ByVal empId As String)
            Me.GetHREmpByEmpIdAsync(empId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetHREmpByEmpIdAsync(ByVal empId As String, ByVal userState As Object)
            If (Me.GetHREmpByEmpIdOperationCompleted Is Nothing) Then
                Me.GetHREmpByEmpIdOperationCompleted = AddressOf Me.OnGetHREmpByEmpIdOperationCompleted
            End If
            Me.InvokeAsync("GetHREmpByEmpId", New Object() {empId}, Me.GetHREmpByEmpIdOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetHREmpByEmpIdOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetHREmpByEmpIdCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetHREmpByEmpIdCompleted(Me, New GetHREmpByEmpIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ci.long-beach.ca.us/GetHREmpByDLNo", RequestNamespace:="http://ci.long-beach.ca.us/", ResponseNamespace:="http://ci.long-beach.ca.us/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetHREmpByDLNo(ByVal dlNo As String) As HREmp
            Dim results() As Object = Me.Invoke("GetHREmpByDLNo", New Object() {dlNo})
            Return CType(results(0),HREmp)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetHREmpByDLNoAsync(ByVal dlNo As String)
            Me.GetHREmpByDLNoAsync(dlNo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetHREmpByDLNoAsync(ByVal dlNo As String, ByVal userState As Object)
            If (Me.GetHREmpByDLNoOperationCompleted Is Nothing) Then
                Me.GetHREmpByDLNoOperationCompleted = AddressOf Me.OnGetHREmpByDLNoOperationCompleted
            End If
            Me.InvokeAsync("GetHREmpByDLNo", New Object() {dlNo}, Me.GetHREmpByDLNoOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetHREmpByDLNoOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetHREmpByDLNoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetHREmpByDLNoCompleted(Me, New GetHREmpByDLNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ci.long-beach.ca.us/GetHREmpsActive", RequestNamespace:="http://ci.long-beach.ca.us/", ResponseNamespace:="http://ci.long-beach.ca.us/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetHREmpsActive() As HREmp()
            Dim results() As Object = Me.Invoke("GetHREmpsActive", New Object(-1) {})
            Return CType(results(0),HREmp())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetHREmpsActiveAsync()
            Me.GetHREmpsActiveAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetHREmpsActiveAsync(ByVal userState As Object)
            If (Me.GetHREmpsActiveOperationCompleted Is Nothing) Then
                Me.GetHREmpsActiveOperationCompleted = AddressOf Me.OnGetHREmpsActiveOperationCompleted
            End If
            Me.InvokeAsync("GetHREmpsActive", New Object(-1) {}, Me.GetHREmpsActiveOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetHREmpsActiveOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetHREmpsActiveCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetHREmpsActiveCompleted(Me, New GetHREmpsActiveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ci.long-beach.ca.us/GetHRDepartments", RequestNamespace:="http://ci.long-beach.ca.us/", ResponseNamespace:="http://ci.long-beach.ca.us/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetHRDepartments() As HRDept()
            Dim results() As Object = Me.Invoke("GetHRDepartments", New Object(-1) {})
            Return CType(results(0),HRDept())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetHRDepartmentsAsync()
            Me.GetHRDepartmentsAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetHRDepartmentsAsync(ByVal userState As Object)
            If (Me.GetHRDepartmentsOperationCompleted Is Nothing) Then
                Me.GetHRDepartmentsOperationCompleted = AddressOf Me.OnGetHRDepartmentsOperationCompleted
            End If
            Me.InvokeAsync("GetHRDepartments", New Object(-1) {}, Me.GetHRDepartmentsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetHRDepartmentsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetHRDepartmentsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetHRDepartmentsCompleted(Me, New GetHRDepartmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ci.long-beach.ca.us/GetHRBureaus", RequestNamespace:="http://ci.long-beach.ca.us/", ResponseNamespace:="http://ci.long-beach.ca.us/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetHRBureaus() As HRBur()
            Dim results() As Object = Me.Invoke("GetHRBureaus", New Object(-1) {})
            Return CType(results(0),HRBur())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetHRBureausAsync()
            Me.GetHRBureausAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetHRBureausAsync(ByVal userState As Object)
            If (Me.GetHRBureausOperationCompleted Is Nothing) Then
                Me.GetHRBureausOperationCompleted = AddressOf Me.OnGetHRBureausOperationCompleted
            End If
            Me.InvokeAsync("GetHRBureaus", New Object(-1) {}, Me.GetHRBureausOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetHRBureausOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetHRBureausCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetHRBureausCompleted(Me, New GetHRBureausCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ci.long-beach.ca.us/GetHRDivisions", RequestNamespace:="http://ci.long-beach.ca.us/", ResponseNamespace:="http://ci.long-beach.ca.us/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetHRDivisions() As HRDiv()
            Dim results() As Object = Me.Invoke("GetHRDivisions", New Object(-1) {})
            Return CType(results(0),HRDiv())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetHRDivisionsAsync()
            Me.GetHRDivisionsAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetHRDivisionsAsync(ByVal userState As Object)
            If (Me.GetHRDivisionsOperationCompleted Is Nothing) Then
                Me.GetHRDivisionsOperationCompleted = AddressOf Me.OnGetHRDivisionsOperationCompleted
            End If
            Me.InvokeAsync("GetHRDivisions", New Object(-1) {}, Me.GetHRDivisionsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetHRDivisionsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetHRDivisionsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetHRDivisionsCompleted(Me, New GetHRDivisionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ci.long-beach.ca.us/GetHRClassifications", RequestNamespace:="http://ci.long-beach.ca.us/", ResponseNamespace:="http://ci.long-beach.ca.us/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetHRClassifications() As HRClass()
            Dim results() As Object = Me.Invoke("GetHRClassifications", New Object(-1) {})
            Return CType(results(0),HRClass())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetHRClassificationsAsync()
            Me.GetHRClassificationsAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetHRClassificationsAsync(ByVal userState As Object)
            If (Me.GetHRClassificationsOperationCompleted Is Nothing) Then
                Me.GetHRClassificationsOperationCompleted = AddressOf Me.OnGetHRClassificationsOperationCompleted
            End If
            Me.InvokeAsync("GetHRClassifications", New Object(-1) {}, Me.GetHRClassificationsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetHRClassificationsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetHRClassificationsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetHRClassificationsCompleted(Me, New GetHRClassificationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ci.long-beach.ca.us/")>  _
    Partial Public Class HREmp
        
        Private empIdField As String
        
        Private pinField As String
        
        Private statusField As String
        
        Private fNameField As String
        
        Private mNameField As String
        
        Private lNameField As String
        
        Private suffixField As String
        
        Private deptField As String
        
        Private deptDescField As String
        
        Private orgField As String
        
        Private orgDescField As String
        
        Private clsField As String
        
        Private classDescField As String
        
        Private dLNoField As String
        
        '''<remarks/>
        Public Property EmpId() As String
            Get
                Return Me.empIdField
            End Get
            Set
                Me.empIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Pin() As String
            Get
                Return Me.pinField
            End Get
            Set
                Me.pinField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FName() As String
            Get
                Return Me.fNameField
            End Get
            Set
                Me.fNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MName() As String
            Get
                Return Me.mNameField
            End Get
            Set
                Me.mNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LName() As String
            Get
                Return Me.lNameField
            End Get
            Set
                Me.lNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Suffix() As String
            Get
                Return Me.suffixField
            End Get
            Set
                Me.suffixField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Dept() As String
            Get
                Return Me.deptField
            End Get
            Set
                Me.deptField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DeptDesc() As String
            Get
                Return Me.deptDescField
            End Get
            Set
                Me.deptDescField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Org() As String
            Get
                Return Me.orgField
            End Get
            Set
                Me.orgField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OrgDesc() As String
            Get
                Return Me.orgDescField
            End Get
            Set
                Me.orgDescField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cls() As String
            Get
                Return Me.clsField
            End Get
            Set
                Me.clsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClassDesc() As String
            Get
                Return Me.classDescField
            End Get
            Set
                Me.classDescField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DLNo() As String
            Get
                Return Me.dLNoField
            End Get
            Set
                Me.dLNoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ci.long-beach.ca.us/")>  _
    Partial Public Class HRClass
        
        Private clsField As String
        
        Private titleField As String
        
        Private typeField As String
        
        '''<remarks/>
        Public Property Cls() As String
            Get
                Return Me.clsField
            End Get
            Set
                Me.clsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ci.long-beach.ca.us/")>  _
    Partial Public Class HRDiv
        
        Private divCodeField As String
        
        Private divNameField As String
        
        Private fromDateField As Date
        
        Private toDateField As Date
        
        Private cityMgrDeptField As String
        
        Private persUnitCodeField As String
        
        Private famisOrgField As String
        
        Private famisIndexField As String
        
        '''<remarks/>
        Public Property DivCode() As String
            Get
                Return Me.divCodeField
            End Get
            Set
                Me.divCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DivName() As String
            Get
                Return Me.divNameField
            End Get
            Set
                Me.divNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FromDate() As Date
            Get
                Return Me.fromDateField
            End Get
            Set
                Me.fromDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ToDate() As Date
            Get
                Return Me.toDateField
            End Get
            Set
                Me.toDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CityMgrDept() As String
            Get
                Return Me.cityMgrDeptField
            End Get
            Set
                Me.cityMgrDeptField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PersUnitCode() As String
            Get
                Return Me.persUnitCodeField
            End Get
            Set
                Me.persUnitCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FamisOrg() As String
            Get
                Return Me.famisOrgField
            End Get
            Set
                Me.famisOrgField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FamisIndex() As String
            Get
                Return Me.famisIndexField
            End Get
            Set
                Me.famisIndexField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ci.long-beach.ca.us/")>  _
    Partial Public Class HRBur
        
        Private burCodeField As String
        
        Private burNameField As String
        
        Private fromDateField As Date
        
        Private toDateField As Date
        
        '''<remarks/>
        Public Property BurCode() As String
            Get
                Return Me.burCodeField
            End Get
            Set
                Me.burCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BurName() As String
            Get
                Return Me.burNameField
            End Get
            Set
                Me.burNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FromDate() As Date
            Get
                Return Me.fromDateField
            End Get
            Set
                Me.fromDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ToDate() As Date
            Get
                Return Me.toDateField
            End Get
            Set
                Me.toDateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ci.long-beach.ca.us/")>  _
    Partial Public Class HRDept
        
        Private deptCodeField As String
        
        Private deptNameField As String
        
        Private famisOrgField As String
        
        Private fromDateField As Date
        
        Private toDateField As Date
        
        '''<remarks/>
        Public Property DeptCode() As String
            Get
                Return Me.deptCodeField
            End Get
            Set
                Me.deptCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DeptName() As String
            Get
                Return Me.deptNameField
            End Get
            Set
                Me.deptNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FamisOrg() As String
            Get
                Return Me.famisOrgField
            End Get
            Set
                Me.famisOrgField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FromDate() As Date
            Get
                Return Me.fromDateField
            End Get
            Set
                Me.fromDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ToDate() As Date
            Get
                Return Me.toDateField
            End Get
            Set
                Me.toDateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub GetHREmpByEmpIdCompletedEventHandler(ByVal sender As Object, ByVal e As GetHREmpByEmpIdCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetHREmpByEmpIdCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As HREmp
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),HREmp)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub GetHREmpByDLNoCompletedEventHandler(ByVal sender As Object, ByVal e As GetHREmpByDLNoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetHREmpByDLNoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As HREmp
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),HREmp)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub GetHREmpsActiveCompletedEventHandler(ByVal sender As Object, ByVal e As GetHREmpsActiveCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetHREmpsActiveCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As HREmp()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),HREmp())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub GetHRDepartmentsCompletedEventHandler(ByVal sender As Object, ByVal e As GetHRDepartmentsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetHRDepartmentsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As HRDept()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),HRDept())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub GetHRBureausCompletedEventHandler(ByVal sender As Object, ByVal e As GetHRBureausCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetHRBureausCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As HRBur()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),HRBur())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub GetHRDivisionsCompletedEventHandler(ByVal sender As Object, ByVal e As GetHRDivisionsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetHRDivisionsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As HRDiv()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),HRDiv())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub GetHRClassificationsCompletedEventHandler(ByVal sender As Object, ByVal e As GetHRClassificationsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetHRClassificationsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As HRClass()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),HRClass())
            End Get
        End Property
    End Class
End Namespace
