'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SiteMaster
    
    '''<summary>
    '''HeadContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''lnkAppName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAppName As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''ulNavBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ulNavBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liMyPackets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liMyPackets As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liReleases control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liReleases As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liPolicyAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liPolicyAdmin As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liSchedules control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liSchedules As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liPolicies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liPolicies As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liRecipGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liRecipGroups As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liPolicyAdmins control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liPolicyAdmins As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liOrgAdmins control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liOrgAdmins As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liPreferences control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liPreferences As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liSettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liCommonCodes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liCommonCodes As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liMessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liMessages As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liNotices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liNotices As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liDepartments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liDepartments As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liBureaus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liBureaus As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liDivisions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liDivisions As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liClassifications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liClassifications As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liEmployees As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liAppUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liAppUsers As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLogin As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''userName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userName As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblPipe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPipe As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LoginStatus1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoginStatus1 As Global.System.Web.UI.WebControls.LoginStatus
    
    '''<summary>
    '''noticeAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noticeAlert As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''noticeMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noticeMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''MainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
