'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Bureau
    Public Property BurCode As String
    Public Property BurDesc As String
    Public Property DeptCode As String
    Public Property Disabled As Boolean
    Public Property CreateDT As Date
    Public Property CreateUser As String
    Public Property LastUpdateDT As Date
    Public Property LastUpdateUser As String

    Public Overridable Property Department As Department
    Public Overridable Property Divisions As ICollection(Of Division) = New HashSet(Of Division)

End Class
