'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Classification
    Public Property ClassCode As String
    Public Property ClassDesc As String
    Public Property ClassType As String
    Public Property Disabled As Boolean
    Public Property CreateDT As Date
    Public Property CreateUser As String
    Public Property LastUpdateDT As Date
    Public Property LastUpdateUser As String

    Public Overridable Property RecipGroups As ICollection(Of RecipGroup) = New HashSet(Of RecipGroup)

End Class
