'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Division
    Public Property DivCode As String
    Public Property DivDesc As String
    Public Property BurCode As String
    Public Property CMDept As String
    Public Property PersUnitCode As String
    Public Property FamisOrg As String
    Public Property FamisDefaultIndex As String
    Public Property Disabled As Boolean
    Public Property CreateDT As Date
    Public Property CreateUser As String
    Public Property LastUpdateDT As Date
    Public Property LastUpdateUser As String

    Public Overridable Property Bureau As Bureau
    Public Overridable Property ReleaseRecipients As ICollection(Of ReleaseRecipient) = New HashSet(Of ReleaseRecipient)

End Class
