'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Employee
    Public Property EmpId As String
    Public Property PIN As String
    Public Property Status As String
    Public Property FirstName As String
    Public Property MiddleName As String
    Public Property LastName As String
    Public Property Suffix As String
    Public Property OrgCode As String
    Public Property ClassCode As String
    Public Property HireDate As Nullable(Of Date)
    Public Property Disabled As Boolean
    Public Property CreateDT As Date
    Public Property LastUpdateDT As Date

    Public Overridable Property RecipGroups As ICollection(Of RecipGroup) = New HashSet(Of RecipGroup)

End Class
