'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Notice
    Public Property NoticeId As Integer
    Public Property NoticeTitle As String
    Public Property NoticeText As String
    Public Property StartDate As Date
    Public Property EndDate As Date
    Public Property DispOrder As Nullable(Of Integer)
    Public Property Disabled As Boolean
    Public Property CreateDT As Date
    Public Property CreateUser As String
    Public Property LastUpdateDT As Date
    Public Property LastUpdateUser As String

End Class
