'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrgAdminNotice
    Public Property ReleaseNoticeId As Integer
    Public Property From As String
    Public Property [To] As String
    Public Property Subject As String
    Public Property Body As String
    Public Property CreateDT As Date
    Public Property SentDT As Nullable(Of Date)

    Public Overridable Property ReleaseNotice As ReleaseNotice

End Class
