'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PacketAckFile
    Public Property ReleaseId As Integer
    Public Property RecipientId As String
    Public Property FileId As String
    Public Property Disabled As Boolean

    Public Overridable Property UploadFile As UploadFile
    Public Overridable Property ReleaseRecipient As ReleaseRecipient

End Class
