'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Policy
    Public Property PolicyId As Integer
    Public Property PolicyName As String
    Public Property PolicyDesc As String
    Public Property ShowDisclaimer As Boolean
    Public Property Disclaimer As String
    Public Property ShareType As String
    Public Property DeptCode As String
    Public Property Disabled As Boolean
    Public Property CreateDT As Date
    Public Property CreateUser As String
    Public Property LastUpdateDT As Date
    Public Property LastUpdateUser As String

    Public Overridable Property PolicyOwners As ICollection(Of PolicyOwner) = New HashSet(Of PolicyOwner)
    Public Overridable Property ReleasePolicies As ICollection(Of ReleasePolicy) = New HashSet(Of ReleasePolicy)
    Public Overridable Property Schedules As ICollection(Of Schedule) = New HashSet(Of Schedule)
    Public Overridable Property UploadFiles As ICollection(Of UploadFile) = New HashSet(Of UploadFile)

End Class
