'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Preference
    Public Property Catg As String
    Public Property UserId As String
    Public Property Val As String
    Public Property LastUpdateDT As Date
    Public Property LastUpdateUser As String

End Class
