'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ReleaseNotice
    Public Property ReleaseNoticeId As Integer
    Public Property ReleaseId As Integer
    Public Property NoticeType As String
    Public Property NoticeDate As Date
    Public Property StartDT As Nullable(Of Date)
    Public Property CompleteDT As Nullable(Of Date)
    Public Property CreateDT As Date
    Public Property CreateUser As String
    Public Property LastUpdateDT As Date
    Public Property LastUpdateUser As String

    Public Overridable Property OrgAdminNotice As OrgAdminNotice
    Public Overridable Property RecipientNotices As ICollection(Of RecipientNotice) = New HashSet(Of RecipientNotice)
    Public Overridable Property Release As Release

End Class
