'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Release
    Public Property ReleaseId As Integer
    Public Property ScheduleId As Integer
    Public Property ReleaseDate As Date
    Public Property DeadlineDate As Date
    Public Property [To] As String
    Public Property From As String
    Public Property Subject As String
    Public Property Disclaimer As String
    Public Property CreateDT As Date
    Public Property CreateUser As String
    Public Property LastUpdateDT As Date
    Public Property LastUpdateUser As String

    Public Overridable Property ReleasePolicies As ICollection(Of ReleasePolicy) = New HashSet(Of ReleasePolicy)
    Public Overridable Property Schedule As Schedule
    Public Overridable Property ReleaseRecipients As ICollection(Of ReleaseRecipient) = New HashSet(Of ReleaseRecipient)
    Public Overridable Property ReleaseNotices As ICollection(Of ReleaseNotice) = New HashSet(Of ReleaseNotice)

End Class
