'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ReleaseRecipient
    Public Property ReleaseId As Integer
    Public Property RecipientId As String
    Public Property RecipientName As String
    Public Property RecipientEmail As String
    Public Property OrgCode As String
    Public Property AckDT As Nullable(Of Date)
    Public Property AckUserId As String
    Public Property AckClientIP As String
    Public Property RecipientViewDT As Nullable(Of Date)
    Public Property RecipientViewClientIP As String
    Public Property AdminMemo As String
    Public Property Exception As String
    Public Property CreateDT As Date
    Public Property CreateUser As String
    Public Property LastUpdateDT As Date
    Public Property LastUpdateUser As String
    Public Property AckAuthType As String

    Public Overridable Property Release As Release
    Public Overridable Property Division As Division
    Public Overridable Property PacketAckFiles As ICollection(Of PacketAckFile) = New HashSet(Of PacketAckFile)

End Class
