'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ReleasePolicy
    Public Property ReleaseId As Integer
    Public Property PolicyId As Integer
    Public Property PolicyName As String
    Public Property PolicyDesc As String
    Public Property ShowDisclaimer As Boolean
    Public Property Disclaimer As String

    Public Overridable Property Release As Release
    Public Overridable Property UploadFiles As ICollection(Of UploadFile) = New HashSet(Of UploadFile)
    Public Overridable Property Policy As Policy

End Class
