'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Schedule
    Public Property ScheduleId As Integer
    Public Property ScheduleName As String
    Public Property ScheduleDesc As String
    Public Property Frequency As String
    Public Property RepeatMonth As Nullable(Of Short)
    Public Property RepeatDay As Nullable(Of Short)
    Public Property FixedReleaseDate As Nullable(Of Date)
    Public Property DaysToDeadline As Short
    Public Property DaysToReminder As String
    Public Property [To] As String
    Public Property From As String
    Public Property Subject As String
    Public Property Disclaimer As String
    Public Property Disabled As Boolean
    Public Property CreateDT As Date
    Public Property CreateUser As String
    Public Property LastUpdateDT As Date
    Public Property LastUpdateUser As String

    Public Overridable Property Releases As ICollection(Of Release) = New HashSet(Of Release)
    Public Overridable Property ScheduleOwners As ICollection(Of ScheduleOwner) = New HashSet(Of ScheduleOwner)
    Public Overridable Property Policies As ICollection(Of Policy) = New HashSet(Of Policy)
    Public Overridable Property RecipGroups As ICollection(Of RecipGroup) = New HashSet(Of RecipGroup)

End Class
