'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UploadFile
    Public Property FileId As String
    Public Property FileUrl As String
    Public Property FileData As Byte()
    Public Property OriginalName As String
    Public Property ContentType As String
    Public Property Length As Decimal
    Public Property CreateDT As Date
    Public Property CreateUser As String

    Public Overridable Property ReleasePolicies As ICollection(Of ReleasePolicy) = New HashSet(Of ReleasePolicy)
    Public Overridable Property Policies As ICollection(Of Policy) = New HashSet(Of Policy)
    Public Overridable Property PacketAckFiles As ICollection(Of PacketAckFile) = New HashSet(Of PacketAckFile)

End Class
