'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class USState
    Public Property Id As Integer
    Public Property Name As String
    Public Property USPS As String
    Public Property OldGPO As String
    Public Property AP As String
    Public Property FIPS As Nullable(Of Integer)

End Class
